In [43]:
import torch
from torch import nn

In [44]:
def comp_conv2d(conv2d,X):
    X = X.view((1,1)+X.shape)
    Y = conv2d(X)
    return Y.view(Y.shape[2:])

In [62]:
conv2d = nn.Conv2d(in_channels=1,out_channels=1,kernel_size=(2,4),padding=1)

In [74]:
list(conv2d.parameters())

[Parameter containing:
 tensor([[[[ 0.0520,  0.3313, -0.0944, -0.3067],
           [ 0.1631, -0.1631,  0.2143,  0.1469]]]], requires_grad=True),
 Parameter containing:
 tensor([0.3528], requires_grad=True)]

In [76]:
X = torch.rand(8,8)

In [77]:
X

tensor([[0.3071, 0.2293, 0.1980, 0.3017, 0.4989, 0.0729, 0.4440, 0.6901],
        [0.9908, 0.8686, 0.5838, 0.9625, 0.9649, 0.7039, 0.5867, 0.3070],
        [0.7660, 0.5712, 0.4817, 0.9628, 0.4949, 0.0753, 0.1824, 0.0951],
        [0.8314, 0.7899, 0.5693, 0.8867, 0.8812, 0.6821, 0.8693, 0.5379],
        [0.9505, 0.3636, 0.0656, 0.2105, 0.7625, 0.2466, 0.6236, 0.1453],
        [0.3830, 0.0662, 0.3829, 0.6124, 0.2808, 0.9951, 0.5030, 0.1448],
        [0.4342, 0.1703, 0.8018, 0.1944, 0.8352, 0.5662, 0.3415, 0.2516],
        [0.8983, 0.4369, 0.5357, 0.5475, 0.3326, 0.0220, 0.0309, 0.4350]])

In [65]:
Y = comp_conv2d(conv2d,X)
Y.shape

torch.Size([9, 7])

In [69]:
X.view((1,1)+X.shape)

tensor([[[[0.4483, 0.5435, 0.7802, 0.4577, 0.9300, 0.3441, 0.7269, 0.4602],
          [0.1884, 0.6468, 0.5950, 0.4285, 0.7792, 0.7731, 0.5929, 0.6313],
          [0.5635, 0.7854, 0.6549, 0.3817, 0.6771, 0.4003, 0.8342, 0.3016],
          [0.7585, 0.3420, 0.7159, 0.7452, 0.9926, 0.3002, 0.1141, 0.9406],
          [0.6275, 0.9018, 0.2602, 0.6920, 0.5311, 0.1054, 0.6560, 0.9605],
          [0.2374, 0.0752, 0.6937, 0.5189, 0.3306, 0.3383, 0.3130, 0.4924],
          [0.2083, 0.7087, 0.7715, 0.0776, 0.3144, 0.5793, 0.4307, 0.1706],
          [0.2404, 0.8941, 0.4376, 0.6845, 0.1529, 0.7587, 0.1516, 0.0748]]]])

In [58]:
X.view((1,1)+X.shape).shape

torch.Size([1, 1, 8, 8])

In [70]:
Y = comp_conv2d(conv2d,X)

In [71]:
Y

tensor([[0.5108, 0.5717, 0.5489, 0.6552, 0.4563, 0.6717, 0.3890],
        [0.4059, 0.4578, 0.5258, 0.6593, 0.6248, 0.5261, 0.7327],
        [0.3442, 0.5495, 0.5066, 0.4634, 0.5385, 0.6680, 0.5236],
        [0.3192, 0.7941, 0.6113, 0.5786, 0.3440, 0.6248, 0.8533],
        [0.4813, 0.3220, 0.5638, 0.5099, 0.8022, 0.5557, 0.4334],
        [0.4750, 0.6986, 0.3165, 0.6621, 0.5027, 0.1969, 0.5945],
        [0.4428, 0.2605, 0.4887, 0.6914, 0.5101, 0.3756, 0.4883],
        [0.3349, 0.5894, 0.7850, 0.3152, 0.5457, 0.4127, 0.6245],
        [0.2138, 0.4102, 0.4326, 0.3551, 0.3208, 0.5748, 0.4354]],
       grad_fn=<ViewBackward>)

In [75]:
conv2d = nn.Conv2d(1,1,kernel_size=3,padding=1,stride=2)

In [78]:
comp_conv2d(conv2d, X).shape

torch.Size([4, 4])

In [79]:
conv2d = nn.Conv2d(1,1,kernel_size=(3,5),padding=(0,1),stride=(3,4))

In [80]:
comp_conv2d(conv2d, X).shape

torch.Size([2, 2])