模型参数的访问、初始化与共享

In [1]:
import torch
from torch import nn
from torch.nn import init

In [2]:
net = nn.Sequential(nn.Linear(4,3),nn.ReLU(),nn.Linear(3,1)) #pytorch已经初始化
print(net)

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [4]:
X = torch.rand(2,4)
print(net(X))
Y = net(X).sum()
print(Y)

tensor([[0.5015],
        [0.5197]], grad_fn=<AddmmBackward>)
tensor(1.0212, grad_fn=<SumBackward0>)


In [5]:
print(type(net.named_parameters())) #返回所有参数的生成器(参数+名字)

<class 'generator'>


In [8]:
for name,param in net.named_parameters():
    print(name,param.size())

0.weight torch.Size([3, 4])
0.bias torch.Size([3])
2.weight torch.Size([1, 3])
2.bias torch.Size([1])


In [9]:
for name,param in net[0].named_parameters():
    print(name,param.size(),type(param))

weight torch.Size([3, 4]) <class 'torch.nn.parameter.Parameter'>
bias torch.Size([3]) <class 'torch.nn.parameter.Parameter'>


In [10]:
weight_0 = list(net[0].parameters())[0]
print(weight_0.data)
print(weight_0.grad) # 反向传播前梯度为None
Y.backward()
print(weight_0.grad)

tensor([[-0.1473, -0.4983, -0.0661,  0.4800],
        [-0.3302,  0.4111, -0.3033,  0.3656],
        [-0.1084,  0.4901, -0.1720,  0.2880]])
None
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.3379, 0.1800, 0.3595, 0.3971],
        [0.0000, 0.0000, 0.0000, 0.0000]])


In [13]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init.normal_(param,mean=0,std=0.01)
        print(name,param.data)
    if 'bias' in name:
        init.constant_(param,val=0)
        print(name,param.data)

0.weight tensor([[-0.0039, -0.0032,  0.0161, -0.0029],
        [-0.0155,  0.0068,  0.0015,  0.0121],
        [-0.0034, -0.0013, -0.0006, -0.0029]])
0.bias tensor([0., 0., 0.])
2.weight tensor([[0.0019, 0.0029, 0.0041]])
2.bias tensor([0.])


In [14]:
def normal_(tensor,mean=0,std=1):
    with torch.no_grad():
        return tensor.normal_(mean,std)

In [15]:
def inin_weight(tensor):
    with torch.no_grad():
        tensor.uniform_(-10,10)
        tensor *= (tensor.abs() >= 5).float()
for name,param in net.named_parameters():
    if 'weight' in name:
        inin_weight(param)
        print(name,param.data)

0.weight tensor([[ 9.9229, -0.0000, -0.0000,  0.0000],
        [-0.0000, -7.1262, -0.0000,  7.1127],
        [ 9.9889,  9.7011, -6.0404,  8.6419]])
2.weight tensor([[7.0266, 8.8175, 8.0428]])


In [ ]:
5