In [1]:
import torch
from torch import nn

In [2]:
class CenteredLayder(nn.Module):
    def __init__(self,**kwargs):
        super(CenteredLayder,self).__init__(**kwargs)
    def forward(self,x):
        return x - x.mean()

In [3]:
layer = CenteredLayder()
layer(torch.tensor([1,2,3,4,5],dtype = torch.float))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayder())

In [5]:
net

Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): CenteredLayder()
)

In [6]:
y = net(torch.rand(4,8))

In [7]:
y.mean().item()

0.0

In [8]:
class MyDense(nn.Module):
    def __init__(self):
        super(MyDense, self).__init__()
        self.params = nn.ParameterList([nn.Parameter(torch.randn(4, 4)) for i in range(3)])
        self.params.append(nn.Parameter(torch.randn(4, 1)))

    def forward(self, x):
        for i in range(len(self.params)):
            x = torch.mm(x, self.params[i])
        return x

In [9]:
net = MyDense()
print(net)

MyDense(
  (params): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 4x4]
      (1): Parameter containing: [torch.FloatTensor of size 4x4]
      (2): Parameter containing: [torch.FloatTensor of size 4x4]
      (3): Parameter containing: [torch.FloatTensor of size 4x1]
  )
)


In [10]:
class MyDictDense(nn.Module):
    def __init__(self):
        super(MyDictDense, self).__init__()
        self.params = nn.ParameterDict({
                'linear1': nn.Parameter(torch.randn(4, 4)),
                'linear2': nn.Parameter(torch.randn(4, 1))
        })
        self.params.update({'linear3': nn.Parameter(torch.randn(4, 2))}) # 新增

    def forward(self, x, choice='linear1'):
        return torch.mm(x, self.params[choice])

net = MyDictDense()
print(net)


MyDictDense(
  (params): ParameterDict(
      (linear1): Parameter containing: [torch.FloatTensor of size 4x4]
      (linear2): Parameter containing: [torch.FloatTensor of size 4x1]
      (linear3): Parameter containing: [torch.FloatTensor of size 4x2]
  )
)


In [15]:
net = nn.Sequential(
    MyDictDense(),
    MyDense(),
)
print(net)

Sequential(
  (0): MyDictDense(
    (params): ParameterDict(
        (linear1): Parameter containing: [torch.FloatTensor of size 4x4]
        (linear2): Parameter containing: [torch.FloatTensor of size 4x1]
        (linear3): Parameter containing: [torch.FloatTensor of size 4x2]
    )
  )
  (1): MyDense(
    (params): ParameterList(
        (0): Parameter containing: [torch.FloatTensor of size 4x4]
        (1): Parameter containing: [torch.FloatTensor of size 4x4]
        (2): Parameter containing: [torch.FloatTensor of size 4x4]
        (3): Parameter containing: [torch.FloatTensor of size 4x1]
    )
  )
)


In [17]:
x = torch.ones(3)

In [18]:
x

tensor([1., 1., 1.])

In [19]:
torch.save(x,'x.pt')

In [20]:
x2 = torch.load('x.pt')

In [22]:
x2

tensor([1., 1., 1.])

In [23]:
torch.cuda.device_count()

1

In [24]:
torch.cuda.get_device_name(0)

'GeForce GTX 1060'

In [25]:
x = torch.tensor([1,2,3])

In [26]:
x

tensor([1, 2, 3])

In [27]:
x = x.cuda(0)

In [28]:
x

tensor([1, 2, 3], device='cuda:0')

In [29]:
x.device

device(type='cuda', index=0)

In [30]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x


tensor([1, 2, 3], device='cuda:0')

In [31]:
y = x**2

In [32]:
y

tensor([1, 4, 9], device='cuda:0')

In [33]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [34]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [37]:
x = torch.rand(2,3).cuda()

In [38]:
net(x)

tensor([[-0.2204],
        [-0.1158]], device='cuda:0', grad_fn=<AddmmBackward>)